#!/bin/sh
#
# students must NOT change this file in any way!!!
PATH=/bin:/usr/bin
TESTNAME="$1"
shift
ARGS=$*

# this is the correct output
# it uses the "REAL" diff program from the operating system
find ${ARGS} > ${TESTNAME}.correct 

# don't change anything else
echo "Running command: ./find" $ARGS
./find ${ARGS} > ${TESTNAME}.myoutput
if cmp -s ${TESTNAME}.correct ${TESTNAME}.myoutput; then
    echo "+++ PASSES ${TESTNAME}"; 
    exit 0
else
    echo "--- FAILS ${TESTNAME}"; 
    diff ${TESTNAME}.correct ${TESTNAME}.myoutput | cat -vet
    exit 99
fi